schema:
  - http://localhost:3000/graphql
documents: gumma-groups/src/schema/**/*.ts
extensions:
  codegen:
    overwrite: true
    ignoreNoDocumens: true
    generates:
      ./gumma-groups/src/graphql/__generated__/:
        preset: client
        presetConfig:
          gqlTagName: gql